# Generated by Django 5.2.6 on 2025-09-13 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_worth', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('monthly_spending', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('investments', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('credit_score', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
